#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_CarryStartInteractionActor

#include "Basic.hpp"

#include "B_InteractionActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_CarryStartInteractionActor.B_CarryStartInteractionActor_C
// 0x0030 (0x0338 - 0x0308)
class AB_CarryStartInteractionActor_C final : public AB_InteractionActor_C
{
public:
	class UStaticMeshComponent*                   Contents5;                                         // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Contents2;                                         // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Contents4;                                         // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Contents3;                                         // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Contents1;                                         // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Contents;                                          // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void Act();
	void Highlight();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_CarryStartInteractionActor_C">();
	}
	static class AB_CarryStartInteractionActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_CarryStartInteractionActor_C>();
	}
};
static_assert(alignof(AB_CarryStartInteractionActor_C) == 0x000008, "Wrong alignment on AB_CarryStartInteractionActor_C");
static_assert(sizeof(AB_CarryStartInteractionActor_C) == 0x000338, "Wrong size on AB_CarryStartInteractionActor_C");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents5) == 0x000308, "Member 'AB_CarryStartInteractionActor_C::Contents5' has a wrong offset!");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents2) == 0x000310, "Member 'AB_CarryStartInteractionActor_C::Contents2' has a wrong offset!");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents4) == 0x000318, "Member 'AB_CarryStartInteractionActor_C::Contents4' has a wrong offset!");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents3) == 0x000320, "Member 'AB_CarryStartInteractionActor_C::Contents3' has a wrong offset!");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents1) == 0x000328, "Member 'AB_CarryStartInteractionActor_C::Contents1' has a wrong offset!");
static_assert(offsetof(AB_CarryStartInteractionActor_C, Contents) == 0x000330, "Member 'AB_CarryStartInteractionActor_C::Contents' has a wrong offset!");

}

