#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_ConnectivityWatcher

#include "Basic.hpp"

#include "B_ConnectivityWatcher_classes.hpp"
#include "B_ConnectivityWatcher_parameters.hpp"


namespace SDK
{

// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.ConnectivityChangedHandler
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// E_ConnectivityType                      Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::ConnectivityChangedHandler(E_ConnectivityType Type, E_ConnectivityState OldState, E_ConnectivityState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "ConnectivityChangedHandler");

	Params::B_ConnectivityWatcher_C_ConnectivityChangedHandler Parms{};

	Parms.Type = Type;
	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.ExecuteUbergraph_B_ConnectivityWatcher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::ExecuteUbergraph_B_ConnectivityWatcher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "ExecuteUbergraph_B_ConnectivityWatcher");

	Params::B_ConnectivityWatcher_C_ExecuteUbergraph_B_ConnectivityWatcher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.Initialize
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGameInstance*                    InGameInstance                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::Initialize(class UGameInstance* InGameInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "Initialize");

	Params::B_ConnectivityWatcher_C_Initialize Parms{};

	Parms.InGameInstance = InGameInstance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.OnConnectivityChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_ConnectivityType                      Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::OnConnectivityChanged__DelegateSignature(E_ConnectivityType Type, E_ConnectivityState OldState, E_ConnectivityState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "OnConnectivityChanged__DelegateSignature");

	Params::B_ConnectivityWatcher_C_OnConnectivityChanged__DelegateSignature Parms{};

	Parms.Type = Type;
	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.SetConnectivityState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_ConnectivityType                      Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::SetConnectivityState(E_ConnectivityType Type, E_ConnectivityState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "SetConnectivityState");

	Params::B_ConnectivityWatcher_C_SetConnectivityState Parms{};

	Parms.Type = Type;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.GetConnectivityState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// E_ConnectivityType                      Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_ConnectivityState                     State                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::GetConnectivityState(E_ConnectivityType Type, E_ConnectivityState* State) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "GetConnectivityState");

	Params::B_ConnectivityWatcher_C_GetConnectivityState Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);

	if (State != nullptr)
		*State = Parms.State;
}


// Function B_ConnectivityWatcher.B_ConnectivityWatcher_C.IsConnectedTo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// E_ConnectivityType                      Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsConnected                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_ConnectivityWatcher_C::IsConnectedTo(E_ConnectivityType Type, bool* IsConnected) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ConnectivityWatcher_C", "IsConnectedTo");

	Params::B_ConnectivityWatcher_C_IsConnectedTo Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);

	if (IsConnected != nullptr)
		*IsConnected = Parms.IsConnected;
}

}

