#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_MapBag

#include "Basic.hpp"

#include "B_StaticMeshProp_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_MapBag.B_MapBag_C
// 0x0000 (0x0590 - 0x0590)
class AB_MapBag_C final : public AB_StaticMeshProp_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_MapBag_C">();
	}
	static class AB_MapBag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_MapBag_C>();
	}
};
static_assert(alignof(AB_MapBag_C) == 0x000010, "Wrong alignment on AB_MapBag_C");
static_assert(sizeof(AB_MapBag_C) == 0x000590, "Wrong size on AB_MapBag_C");

}

