#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_MagicRelict

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "EHighlightChannel_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_MagicRelict.B_MagicRelict_C
// 0x0068 (0x02F8 - 0x0290)
class AB_MagicRelict_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_MagicDust;                                      // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       UI;                                                // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Audio;                                             // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   OutlineShape;                                      // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Sphere;                                            // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UProjectileMovementComponent*           ProjectileMovement;                                // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class APlayerState*                           OwningPlayerState;                                 // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FVector                                Velocity;                                          // 0x02D0(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsHighlighted;                                     // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         RemaingLifeSpan;                                   // 0x02E9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EA[0x6];                                      // 0x02EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 OtherActorOverlap;                                 // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_B_MagicRelict(int32 EntryPoint);
	void HandleIsOwning(bool Owning);
	void OnOwnerDestroyed(class AActor* DestroyedActor);
	void OnOwnerKilled(class AController* Killer);
	void OnPropOwnerDestroyed(class AActor* DestroyedActor);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void RefreshHighlight(bool* Highlightable);
	void SetHighlight(bool Highlighted, bool* ForcedBoolean);
	void SetHighlightChannel(EHighlightChannel Channel);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_MagicRelict_C">();
	}
	static class AB_MagicRelict_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_MagicRelict_C>();
	}
};
static_assert(alignof(AB_MagicRelict_C) == 0x000008, "Wrong alignment on AB_MagicRelict_C");
static_assert(sizeof(AB_MagicRelict_C) == 0x0002F8, "Wrong size on AB_MagicRelict_C");
static_assert(offsetof(AB_MagicRelict_C, UberGraphFrame) == 0x000290, "Member 'AB_MagicRelict_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, NS_MagicDust) == 0x000298, "Member 'AB_MagicRelict_C::NS_MagicDust' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, UI) == 0x0002A0, "Member 'AB_MagicRelict_C::UI' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, Audio) == 0x0002A8, "Member 'AB_MagicRelict_C::Audio' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, OutlineShape) == 0x0002B0, "Member 'AB_MagicRelict_C::OutlineShape' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, Sphere) == 0x0002B8, "Member 'AB_MagicRelict_C::Sphere' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, ProjectileMovement) == 0x0002C0, "Member 'AB_MagicRelict_C::ProjectileMovement' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, OwningPlayerState) == 0x0002C8, "Member 'AB_MagicRelict_C::OwningPlayerState' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, Velocity) == 0x0002D0, "Member 'AB_MagicRelict_C::Velocity' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, IsHighlighted) == 0x0002E8, "Member 'AB_MagicRelict_C::IsHighlighted' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, RemaingLifeSpan) == 0x0002E9, "Member 'AB_MagicRelict_C::RemaingLifeSpan' has a wrong offset!");
static_assert(offsetof(AB_MagicRelict_C, OtherActorOverlap) == 0x0002F0, "Member 'AB_MagicRelict_C::OtherActorOverlap' has a wrong offset!");

}

