#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_PlayerStartDistance

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_PlayerStartDistance.B_PlayerStartDistance_C
// 0x0010 (0x0038 - 0x0028)
class UB_PlayerStartDistance_C final : public UObject
{
public:
	class AB_WitchPlayerStart_C*                  WitchPlayerStart;                                  // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Distance;                                          // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_PlayerStartDistance_C">();
	}
	static class UB_PlayerStartDistance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_PlayerStartDistance_C>();
	}
};
static_assert(alignof(UB_PlayerStartDistance_C) == 0x000008, "Wrong alignment on UB_PlayerStartDistance_C");
static_assert(sizeof(UB_PlayerStartDistance_C) == 0x000038, "Wrong size on UB_PlayerStartDistance_C");
static_assert(offsetof(UB_PlayerStartDistance_C, WitchPlayerStart) == 0x000028, "Member 'UB_PlayerStartDistance_C::WitchPlayerStart' has a wrong offset!");
static_assert(offsetof(UB_PlayerStartDistance_C, Distance) == 0x000030, "Member 'UB_PlayerStartDistance_C::Distance' has a wrong offset!");

}

