#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SabotagePortal

#include "Basic.hpp"

#include "B_SabotagePortal_classes.hpp"
#include "B_SabotagePortal_parameters.hpp"


namespace SDK
{

// Function B_SabotagePortal.B_SabotagePortal_C.CheckEnteredCode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UB_EnteredPortalCode_C*           PortalCode                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_SabotagePortal_C::CheckEnteredCode(class UB_EnteredPortalCode_C* PortalCode, int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "CheckEnteredCode");

	Params::B_SabotagePortal_C_CheckEnteredCode Parms{};

	Parms.PortalCode = PortalCode;
	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_SabotagePortal.B_SabotagePortal_C.ExecuteUbergraph_B_SabotagePortal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_SabotagePortal_C::ExecuteUbergraph_B_SabotagePortal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "ExecuteUbergraph_B_SabotagePortal");

	Params::B_SabotagePortal_C_ExecuteUbergraph_B_SabotagePortal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_SabotagePortal.B_SabotagePortal_C.IsActive
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AB_SabotagePortal_C::IsActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "IsActive");

	Params::B_SabotagePortal_C_IsActive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function B_SabotagePortal.B_SabotagePortal_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_SabotagePortal_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "ReceiveTick");

	Params::B_SabotagePortal_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_SabotagePortal.B_SabotagePortal_C.Sabotage
// (Public, BlueprintCallable, BlueprintEvent)

void AB_SabotagePortal_C::Sabotage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "Sabotage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_SabotagePortal.B_SabotagePortal_C.Stop
// (Public, BlueprintCallable, BlueprintEvent)

void AB_SabotagePortal_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_SabotagePortal.B_SabotagePortal_C.StopPortal
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_SabotagePortal_C::StopPortal(int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "StopPortal");

	Params::B_SabotagePortal_C_StopPortal Parms{};

	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_SabotagePortal.B_SabotagePortal_C.TickBomb
// (Public, BlueprintCallable, BlueprintEvent)

void AB_SabotagePortal_C::TickBomb()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_SabotagePortal_C", "TickBomb");

	UObject::ProcessEvent(Func, nullptr);
}

}

