#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SkinHunterRangedWeaponDefault

#include "Basic.hpp"

#include "B_SkinHunterRangedWeaponBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_SkinHunterRangedWeaponDefault.B_SkinHunterRangedWeaponDefault_C
// 0x0000 (0x02D0 - 0x02D0)
class AB_SkinHunterRangedWeaponDefault_C final : public AB_SkinHunterRangedWeaponBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_SkinHunterRangedWeaponDefault_C">();
	}
	static class AB_SkinHunterRangedWeaponDefault_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_SkinHunterRangedWeaponDefault_C>();
	}
};
static_assert(alignof(AB_SkinHunterRangedWeaponDefault_C) == 0x000008, "Wrong alignment on AB_SkinHunterRangedWeaponDefault_C");
static_assert(sizeof(AB_SkinHunterRangedWeaponDefault_C) == 0x0002D0, "Wrong size on AB_SkinHunterRangedWeaponDefault_C");

}

