#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SkinHunterUpperBodyColorize

#include "Basic.hpp"

#include "B_SkinHunterUpperBodyBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_SkinHunterUpperBodyColorize.B_SkinHunterUpperBodyColorize_C
// 0x0000 (0x02D0 - 0x02D0)
class AB_SkinHunterUpperBodyColorize_C final : public AB_SkinHunterUpperBodyBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_SkinHunterUpperBodyColorize_C">();
	}
	static class AB_SkinHunterUpperBodyColorize_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_SkinHunterUpperBodyColorize_C>();
	}
};
static_assert(alignof(AB_SkinHunterUpperBodyColorize_C) == 0x000008, "Wrong alignment on AB_SkinHunterUpperBodyColorize_C");
static_assert(sizeof(AB_SkinHunterUpperBodyColorize_C) == 0x0002D0, "Wrong size on AB_SkinHunterUpperBodyColorize_C");

}

