#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SkinHunterHeadCommon05

#include "Basic.hpp"

#include "B_SkinHunterHeadBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_SkinHunterHeadCommon05.B_SkinHunterHeadCommon05_C
// 0x0000 (0x02E8 - 0x02E8)
class AB_SkinHunterHeadCommon05_C : public AB_SkinHunterHeadBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_SkinHunterHeadCommon05_C">();
	}
	static class AB_SkinHunterHeadCommon05_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_SkinHunterHeadCommon05_C>();
	}
};
static_assert(alignof(AB_SkinHunterHeadCommon05_C) == 0x000008, "Wrong alignment on AB_SkinHunterHeadCommon05_C");
static_assert(sizeof(AB_SkinHunterHeadCommon05_C) == 0x0002E8, "Wrong size on AB_SkinHunterHeadCommon05_C");

}

