#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CheckboxAreaButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_CheckboxAreaButton.WB_CheckboxAreaButton_C
// 0x0038 (0x0318 - 0x02E0)
class UWB_CheckboxAreaButton_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWB_CheckBox_C*                         CheckBox;                                          // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextField;                                         // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             Clicked;                                           // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FText                                   Text;                                              // 0x0308(0x0010)(Edit, BlueprintVisible)

public:
	void Clicked__DelegateSignature();
	void ExecuteUbergraph_WB_CheckboxAreaButton(int32 EntryPoint);
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void PreConstruct(bool IsDesignTime);
	void ResetCheckboxStateToDeterminedTest(TArray<class AActor*>& TestActors);
	void SetCheckBoxState(ECheckBoxState InCheckedState);
	void SetCheckboxStateToUndeterminedTest(class AActor* TestActor);

	void GetCheckBoxState(ECheckBoxState* CheckedState) const;
	void GetTestBool(class AActor* TestActor, bool* TestBool) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_CheckboxAreaButton_C">();
	}
	static class UWB_CheckboxAreaButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_CheckboxAreaButton_C>();
	}
};
static_assert(alignof(UWB_CheckboxAreaButton_C) == 0x000008, "Wrong alignment on UWB_CheckboxAreaButton_C");
static_assert(sizeof(UWB_CheckboxAreaButton_C) == 0x000318, "Wrong size on UWB_CheckboxAreaButton_C");
static_assert(offsetof(UWB_CheckboxAreaButton_C, UberGraphFrame) == 0x0002E0, "Member 'UWB_CheckboxAreaButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_CheckboxAreaButton_C, CheckBox) == 0x0002E8, "Member 'UWB_CheckboxAreaButton_C::CheckBox' has a wrong offset!");
static_assert(offsetof(UWB_CheckboxAreaButton_C, TextField) == 0x0002F0, "Member 'UWB_CheckboxAreaButton_C::TextField' has a wrong offset!");
static_assert(offsetof(UWB_CheckboxAreaButton_C, Clicked) == 0x0002F8, "Member 'UWB_CheckboxAreaButton_C::Clicked' has a wrong offset!");
static_assert(offsetof(UWB_CheckboxAreaButton_C, Text) == 0x000308, "Member 'UWB_CheckboxAreaButton_C::Text' has a wrong offset!");

}

