#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_FriendScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK::Params
{

// Function WB_FriendScreen.WB_FriendScreen_C.ExecuteUbergraph_WB_FriendScreen
// 0x02C0 (0x02C0 - 0x0000)
struct WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA1[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMasterServerSubsystem*                 CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window;              // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA2[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNewMasterServerManager*                CallFunc_GetNewMasterServerManager_ReturnValue;    // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       K2Node_CustomEvent_UserId;                         // 0x0040(0x0030)(HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bWasSuccessful;                 // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA3[0x7];                                     // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UB_GameInstance_C*                      K2Node_DynamicCast_AsB_Game_Instance;              // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA4[0x7];                                     // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_1;            // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UB_GameInstance_C*                      K2Node_DynamicCast_AsB_Game_Instance_1;            // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA5[0x7];                                     // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_ShowDialog_Widget;                        // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful)> K2Node_CreateDelegate_OutputDelegate;              // 0x00A8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_2;            // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       Temp_struct_Variable;                              // 0x00C0(0x0030)(HasGetValueTypeHash)
	class UB_GameInstance_C*                      K2Node_DynamicCast_AsB_Game_Instance_2;            // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA6[0x7];                                     // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       K2Node_CustomEvent_UserId_1;                       // 0x0100(0x0030)(HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bWasSuccessful_1;               // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA7[0x3];                                     // 0x0131(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0134(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA8[0x4];                                     // 0x0144(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_3;            // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UB_GameInstance_C*                      K2Node_DynamicCast_AsB_Game_Instance_3;            // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA9[0x6];                                     // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWB_AccountCategoryButton_C*>    K2Node_MakeArray_Array;                            // 0x0160(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UUserWidget*>                    K2Node_MakeArray_Array_1;                          // 0x0170(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UB_GameInstance_C*                      CallFunc_GetBGameInstance_ReturnValue;             // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsCurrentlyInMatch_IsCurrentlyInMatch; // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAA[0x7];                                     // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0190(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UOnlinePresenceSubsystem*               CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x01A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAB[0x7];                                     // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_CreativePlayerController_C*          K2Node_DynamicCast_AsB_Creative_Player_Controller; // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAC[0x3];                                     // 0x01B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x01BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x01CC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAD[0x4];                                     // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x01E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UB_GameInstance_C*                      CallFunc_GetBGameInstance_ReturnValue_1;           // 0x01E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x01F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       CallFunc_GetControllerUniqueNetId_ReturnValue;     // 0x01F8(0x0030)(HasGetValueTypeHash)
	class UOnlinePresenceSubsystemQueryPresence*  CallFunc_QueryPresence_ReturnValue;                // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMasterServerSubsystem*                 CallFunc_GetEngineSubsystem_ReturnValue_1;         // 0x0230(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNewMasterServerManager*                CallFunc_GetNewMasterServerManager_ReturnValue_1;  // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0241(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAE[0x6];                                     // 0x0242(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue_1;            // 0x0248(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window_1;            // 0x0250(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EAF[0x3];                                     // 0x0261(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0264(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB0[0x4];                                     // 0x0274(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue_2;            // 0x0278(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window_2;            // 0x0280(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB1[0x7];                                     // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetCurrentlyFocusedWidget_FocusedWidget;  // 0x0298(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue_3;            // 0x02A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window_3;            // 0x02A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x02B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen) == 0x000008, "Wrong alignment on WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen");
static_assert(sizeof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen) == 0x0002C0, "Wrong size on WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, EntryPoint) == 0x000000, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetActiveWidget_ReturnValue) == 0x000008, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsI_Friend_Window) == 0x000018, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsI_Friend_Window' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetNewMasterServerManager_ReturnValue) == 0x000030, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetNewMasterServerManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetGameInstance_ReturnValue) == 0x000038, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CustomEvent_UserId) == 0x000040, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CustomEvent_UserId' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CustomEvent_bWasSuccessful) == 0x000070, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CustomEvent_bWasSuccessful' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsB_Game_Instance) == 0x000078, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsB_Game_Instance' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_1) == 0x000080, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetGameInstance_ReturnValue_1) == 0x000088, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsB_Game_Instance_1) == 0x000090, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsB_Game_Instance_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_2) == 0x000098, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_ShowDialog_Widget) == 0x0000A0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_ShowDialog_Widget' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CreateDelegate_OutputDelegate) == 0x0000A8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetGameInstance_ReturnValue_2) == 0x0000B8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetGameInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, Temp_struct_Variable) == 0x0000C0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsB_Game_Instance_2) == 0x0000F0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsB_Game_Instance_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_3) == 0x0000F8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CustomEvent_UserId_1) == 0x000100, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CustomEvent_UserId_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CustomEvent_bWasSuccessful_1) == 0x000130, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CustomEvent_bWasSuccessful_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CreateDelegate_OutputDelegate_1) == 0x000134, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetGameInstance_ReturnValue_3) == 0x000148, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetGameInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsB_Game_Instance_3) == 0x000150, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsB_Game_Instance_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_4) == 0x000158, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_Event_IsDesignTime) == 0x000159, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_MakeArray_Array) == 0x000160, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_MakeArray_Array_1) == 0x000170, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetBGameInstance_ReturnValue) == 0x000180, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetBGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetIsCurrentlyInMatch_IsCurrentlyInMatch) == 0x000188, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetIsCurrentlyInMatch_IsCurrentlyInMatch' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000190, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000198, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetOwningPlayer_ReturnValue) == 0x0001A0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, Temp_bool_Variable) == 0x0001A8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsB_Creative_Player_Controller) == 0x0001B0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsB_Creative_Player_Controller' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_5) == 0x0001B8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001BC, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CreateDelegate_OutputDelegate_3) == 0x0001CC, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0001E0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetBGameInstance_ReturnValue_1) == 0x0001E8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetBGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0001F0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetControllerUniqueNetId_ReturnValue) == 0x0001F8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetControllerUniqueNetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_QueryPresence_ReturnValue) == 0x000228, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_QueryPresence_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetEngineSubsystem_ReturnValue_1) == 0x000230, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetEngineSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetNewMasterServerManager_ReturnValue_1) == 0x000238, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetNewMasterServerManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_IsValid_ReturnValue) == 0x000240, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_MakeLiteralByte_ReturnValue) == 0x000241, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetActiveWidget_ReturnValue_1) == 0x000248, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetActiveWidget_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsI_Friend_Window_1) == 0x000250, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsI_Friend_Window_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_6) == 0x000260, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_CreateDelegate_OutputDelegate_4) == 0x000264, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetActiveWidget_ReturnValue_2) == 0x000278, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetActiveWidget_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsI_Friend_Window_2) == 0x000280, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsI_Friend_Window_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_7) == 0x000290, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetCurrentlyFocusedWidget_FocusedWidget) == 0x000298, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetCurrentlyFocusedWidget_FocusedWidget' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_GetActiveWidget_ReturnValue_3) == 0x0002A0, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_GetActiveWidget_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_AsI_Friend_Window_3) == 0x0002A8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_AsI_Friend_Window_3' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, K2Node_DynamicCast_bSuccess_8) == 0x0002B8, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x0002B9, "Member 'WB_FriendScreen_C_ExecuteUbergraph_WB_FriendScreen::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.GetInitialFocusWidget
// 0x0030 (0x0030 - 0x0000)
struct WB_FriendScreen_C_GetInitialFocusWidget final
{
public:
	class UUserWidget*                            InitialFocusWidget;                                // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB2[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window;              // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_GetInitialFocusWidget) == 0x000008, "Wrong alignment on WB_FriendScreen_C_GetInitialFocusWidget");
static_assert(sizeof(WB_FriendScreen_C_GetInitialFocusWidget) == 0x000030, "Wrong size on WB_FriendScreen_C_GetInitialFocusWidget");
static_assert(offsetof(WB_FriendScreen_C_GetInitialFocusWidget, InitialFocusWidget) == 0x000000, "Member 'WB_FriendScreen_C_GetInitialFocusWidget::InitialFocusWidget' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetInitialFocusWidget, CallFunc_GetActiveWidget_ReturnValue) == 0x000008, "Member 'WB_FriendScreen_C_GetInitialFocusWidget::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetInitialFocusWidget, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_GetInitialFocusWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetInitialFocusWidget, K2Node_DynamicCast_AsI_Friend_Window) == 0x000018, "Member 'WB_FriendScreen_C_GetInitialFocusWidget::K2Node_DynamicCast_AsI_Friend_Window' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetInitialFocusWidget, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WB_FriendScreen_C_GetInitialFocusWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.GetWidgetLeftToCurrent
// 0x0040 (0x0040 - 0x0000)
struct WB_FriendScreen_C_GetWidgetLeftToCurrent final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumWidgets_ReturnValue;                // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB3[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB4[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_GetWidgetLeftToCurrent) == 0x000008, "Wrong alignment on WB_FriendScreen_C_GetWidgetLeftToCurrent");
static_assert(sizeof(WB_FriendScreen_C_GetWidgetLeftToCurrent) == 0x000040, "Wrong size on WB_FriendScreen_C_GetWidgetLeftToCurrent");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, ReturnValue) == 0x000000, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000008, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_GetNumWidgets_ReturnValue) == 0x00000C, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_GetNumWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_Subtract_IntInt_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000018, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x000020, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, K2Node_MathExpression_ReturnValue) == 0x000028, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::K2Node_MathExpression_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_FTrunc_ReturnValue) == 0x000030, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetLeftToCurrent, CallFunc_GetWidgetAtIndex_ReturnValue) == 0x000038, "Member 'WB_FriendScreen_C_GetWidgetLeftToCurrent::CallFunc_GetWidgetAtIndex_ReturnValue' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.GetWidgetRightToCurrent
// 0x0040 (0x0040 - 0x0000)
struct WB_FriendScreen_C_GetWidgetRightToCurrent final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumWidgets_ReturnValue;                // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB5[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB6[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_GetWidgetRightToCurrent) == 0x000008, "Wrong alignment on WB_FriendScreen_C_GetWidgetRightToCurrent");
static_assert(sizeof(WB_FriendScreen_C_GetWidgetRightToCurrent) == 0x000040, "Wrong size on WB_FriendScreen_C_GetWidgetRightToCurrent");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, ReturnValue) == 0x000000, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000008, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_GetNumWidgets_ReturnValue) == 0x00000C, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_GetNumWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000018, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x000020, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, K2Node_MathExpression_ReturnValue) == 0x000028, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::K2Node_MathExpression_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_FTrunc_ReturnValue) == 0x000030, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_GetWidgetRightToCurrent, CallFunc_GetWidgetAtIndex_ReturnValue) == 0x000038, "Member 'WB_FriendScreen_C_GetWidgetRightToCurrent::CallFunc_GetWidgetAtIndex_ReturnValue' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6
// 0x0038 (0x0038 - 0x0000)
struct WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6 final
{
public:
	struct FUniqueNetIdRepl                       UserId;                                            // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          bWasSuccessful;                                    // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6) == 0x000008, "Wrong alignment on WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6");
static_assert(sizeof(WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6) == 0x000038, "Wrong size on WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6");
static_assert(offsetof(WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6, UserId) == 0x000000, "Member 'WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6::UserId' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6, bWasSuccessful) == 0x000030, "Member 'WB_FriendScreen_C_OnCallFailed_2BBDE9ED47F12DAA1726459057F076D6::bWasSuccessful' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6
// 0x0038 (0x0038 - 0x0000)
struct WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6 final
{
public:
	struct FUniqueNetIdRepl                       UserId;                                            // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          bWasSuccessful;                                    // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6) == 0x000008, "Wrong alignment on WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6");
static_assert(sizeof(WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6) == 0x000038, "Wrong size on WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6");
static_assert(offsetof(WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6, UserId) == 0x000000, "Member 'WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6::UserId' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6, bWasSuccessful) == 0x000030, "Member 'WB_FriendScreen_C_OnPresenceTaskComplete_2BBDE9ED47F12DAA1726459057F076D6::bWasSuccessful' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.OnPreviewKeyDown
// 0x0398 (0x0398 - 0x0000)
struct WB_FriendScreen_C_OnPreviewKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0078(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0130(0x00B8)()
	struct FEventReply                            CallFunc_OnPreviewKeyDown_ReturnValue;             // 0x01E8(0x00B8)()
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x02A0(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x02B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB7[0x6];                                     // 0x02BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   CallFunc_GetGamepadAcceptKey_ReturnValue;          // 0x02C0(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_2;          // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB8[0x7];                                     // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue_1;                    // 0x02E0(0x00B8)()
};
static_assert(alignof(WB_FriendScreen_C_OnPreviewKeyDown) == 0x000008, "Wrong alignment on WB_FriendScreen_C_OnPreviewKeyDown");
static_assert(sizeof(WB_FriendScreen_C_OnPreviewKeyDown) == 0x000398, "Wrong size on WB_FriendScreen_C_OnPreviewKeyDown");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, MyGeometry) == 0x000000, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, InKeyEvent) == 0x000038, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, ReturnValue) == 0x000078, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue) == 0x000130, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_OnPreviewKeyDown_ReturnValue) == 0x0001E8, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_OnPreviewKeyDown_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_GetKey_ReturnValue) == 0x0002A0, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x0002B8, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x0002B9, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_GetGamepadAcceptKey_ReturnValue) == 0x0002C0, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_GetGamepadAcceptKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_2) == 0x0002D8, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_OnPreviewKeyDown, CallFunc_Handled_ReturnValue_1) == 0x0002E0, "Member 'WB_FriendScreen_C_OnPreviewKeyDown::CallFunc_Handled_ReturnValue_1' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_FriendScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_PreConstruct) == 0x000001, "Wrong alignment on WB_FriendScreen_C_PreConstruct");
static_assert(sizeof(WB_FriendScreen_C_PreConstruct) == 0x000001, "Wrong size on WB_FriendScreen_C_PreConstruct");
static_assert(offsetof(WB_FriendScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WB_FriendScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.SetActiveSwitcherTab
// 0x0060 (0x0060 - 0x0000)
struct WB_FriendScreen_C_SetActiveSwitcherTab final
{
public:
	class UWidget*                                ActiveTab;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UB_GameInstance_C*                      K2Node_DynamicCast_AsB_Game_Instance;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EB9[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window;              // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EBA[0x6];                                     // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class II_FriendWindow_C>     K2Node_DynamicCast_AsI_Friend_Window_1;            // 0x0048(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_SetActiveSwitcherTab) == 0x000008, "Wrong alignment on WB_FriendScreen_C_SetActiveSwitcherTab");
static_assert(sizeof(WB_FriendScreen_C_SetActiveSwitcherTab) == 0x000060, "Wrong size on WB_FriendScreen_C_SetActiveSwitcherTab");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, ActiveTab) == 0x000000, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::ActiveTab' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, CallFunc_GetGameInstance_ReturnValue) == 0x000008, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, CallFunc_GetObjectClass_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_AsB_Game_Instance) == 0x000018, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_AsB_Game_Instance' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, CallFunc_GetActiveWidget_ReturnValue) == 0x000028, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_AsI_Friend_Window) == 0x000030, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_AsI_Friend_Window' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_bSuccess_1) == 0x000040, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, CallFunc_Map_Remove_ReturnValue) == 0x000041, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_AsI_Friend_Window_1) == 0x000048, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_AsI_Friend_Window_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_SetActiveSwitcherTab, K2Node_DynamicCast_bSuccess_2) == 0x000058, "Member 'WB_FriendScreen_C_SetActiveSwitcherTab::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.TabLeft
// 0x0008 (0x0008 - 0x0000)
struct WB_FriendScreen_C_TabLeft final
{
public:
	class UWidget*                                CallFunc_GetWidgetLeftToCurrent_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_TabLeft) == 0x000008, "Wrong alignment on WB_FriendScreen_C_TabLeft");
static_assert(sizeof(WB_FriendScreen_C_TabLeft) == 0x000008, "Wrong size on WB_FriendScreen_C_TabLeft");
static_assert(offsetof(WB_FriendScreen_C_TabLeft, CallFunc_GetWidgetLeftToCurrent_ReturnValue) == 0x000000, "Member 'WB_FriendScreen_C_TabLeft::CallFunc_GetWidgetLeftToCurrent_ReturnValue' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.TabRight
// 0x0008 (0x0008 - 0x0000)
struct WB_FriendScreen_C_TabRight final
{
public:
	class UWidget*                                CallFunc_GetWidgetRightToCurrent_ReturnValue;      // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_TabRight) == 0x000008, "Wrong alignment on WB_FriendScreen_C_TabRight");
static_assert(sizeof(WB_FriendScreen_C_TabRight) == 0x000008, "Wrong size on WB_FriendScreen_C_TabRight");
static_assert(offsetof(WB_FriendScreen_C_TabRight, CallFunc_GetWidgetRightToCurrent_ReturnValue) == 0x000000, "Member 'WB_FriendScreen_C_TabRight::CallFunc_GetWidgetRightToCurrent_ReturnValue' has a wrong offset!");

// Function WB_FriendScreen.WB_FriendScreen_C.UpdateTabButtonStyles
// 0x0040 (0x0040 - 0x0000)
struct WB_FriendScreen_C_UpdateTabButtonStyles final
{
public:
	class UWB_AccountCategoryButton_C*            CurrentButton;                                     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EBB[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWB_AccountCategoryButton_C*            CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Array_Get_Item_1;                         // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EBC[0x3];                                     // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_FriendScreen_C_UpdateTabButtonStyles) == 0x000008, "Wrong alignment on WB_FriendScreen_C_UpdateTabButtonStyles");
static_assert(sizeof(WB_FriendScreen_C_UpdateTabButtonStyles) == 0x000040, "Wrong size on WB_FriendScreen_C_UpdateTabButtonStyles");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CurrentButton) == 0x000000, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CurrentButton' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, Temp_int_Array_Index_Variable) == 0x000008, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_GetActiveWidget_ReturnValue) == 0x000018, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_Array_Get_Item) == 0x000020, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_Array_Get_Item_1) == 0x000028, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000030, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_Array_Length_ReturnValue) == 0x000034, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_FriendScreen_C_UpdateTabButtonStyles, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'WB_FriendScreen_C_UpdateTabButtonStyles::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

