#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_MapCyclePreview

#include "Basic.hpp"

#include "WB_MapCyclePreview_classes.hpp"
#include "WB_MapCyclePreview_parameters.hpp"


namespace SDK
{

// Function WB_MapCyclePreview.WB_MapCyclePreview_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWB_MapCyclePreview_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "GetVisibility_0");

	Params::WB_MapCyclePreview_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWB_MapCyclePreview_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "OnFocusReceived");

	Params::WB_MapCyclePreview_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.SetTitleAndCheckboxState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_MapCyclePreview_C::SetTitleAndCheckboxState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "SetTitleAndCheckboxState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.Get_MapCountText_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWB_MapCyclePreview_C::Get_MapCountText_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "Get_MapCountText_Text_0");

	Params::WB_MapCyclePreview_C_Get_MapCountText_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.GetMapButtonDataByFileName
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           Filename                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
// class UB_MapButtonData_C*               Data                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::GetMapButtonDataByFileName(const class FString& Filename, class UB_MapButtonData_C** Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "GetMapButtonDataByFileName");

	Params::WB_MapCyclePreview_C_GetMapButtonDataByFileName Parms{};

	Parms.Filename = std::move(Filename);

	UObject::ProcessEvent(Func, &Parms);

	if (Data != nullptr)
		*Data = Parms.Data;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.RemoveSelectedMapFromCycle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UB_TileViewData_C*                ItemData                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::RemoveSelectedMapFromCycle(class UB_TileViewData_C* ItemData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "RemoveSelectedMapFromCycle");

	Params::WB_MapCyclePreview_C_RemoveSelectedMapFromCycle Parms{};

	Parms.ItemData = ItemData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.TryAddSelectedMapToCycle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Filename                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
// bool                                    Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::TryAddSelectedMapToCycle(const class FString& Filename, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "TryAddSelectedMapToCycle");

	Params::WB_MapCyclePreview_C_TryAddSelectedMapToCycle Parms{};

	Parms.Filename = std::move(Filename);

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.GetIndividualItemDataAndFocus
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      CategoryButton                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// ESalvageCategory                        SalvageCategory                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UB_TileViewData_C*>        Data                                                   (Parm, OutParm)
// TArray<bool>                            FocusNeeded                                            (Parm, OutParm)

void UWB_MapCyclePreview_C::GetIndividualItemDataAndFocus(class UUserWidget* CategoryButton, ESalvageCategory SalvageCategory, TArray<class UB_TileViewData_C*>* Data, TArray<bool>* FocusNeeded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "GetIndividualItemDataAndFocus");

	Params::WB_MapCyclePreview_C_GetIndividualItemDataAndFocus Parms{};

	Parms.CategoryButton = CategoryButton;
	Parms.SalvageCategory = SalvageCategory;

	UObject::ProcessEvent(Func, &Parms);

	if (Data != nullptr)
		*Data = std::move(Parms.Data);

	if (FocusNeeded != nullptr)
		*FocusNeeded = std::move(Parms.FocusNeeded);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.GetTileView
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTileView*                        TileView                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::GetTileView(class UTileView** TileView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "GetTileView");

	Params::WB_MapCyclePreview_C_GetTileView Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TileView != nullptr)
		*TileView = Parms.TileView;
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.InpActEvt_Gamepad_Special_Left_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::InpActEvt_Gamepad_Special_Left_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "InpActEvt_Gamepad_Special_Left_K2Node_InputKeyEvent_0");

	Params::WB_MapCyclePreview_C_InpActEvt_Gamepad_Special_Left_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_MapCyclePreview_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.BndEvt__WB_MapCyclePreview_RandomCheckbox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::BndEvt__WB_MapCyclePreview_RandomCheckbox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "BndEvt__WB_MapCyclePreview_RandomCheckbox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature");

	Params::WB_MapCyclePreview_C_BndEvt__WB_MapCyclePreview_RandomCheckbox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.OnMapRemoved__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    MapListEmpty                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::OnMapRemoved__DelegateSignature(bool MapListEmpty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "OnMapRemoved__DelegateSignature");

	Params::WB_MapCyclePreview_C_OnMapRemoved__DelegateSignature Parms{};

	Parms.MapListEmpty = MapListEmpty;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_MapCyclePreview.WB_MapCyclePreview_C.ExecuteUbergraph_WB_MapCyclePreview
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_MapCyclePreview_C::ExecuteUbergraph_WB_MapCyclePreview(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MapCyclePreview_C", "ExecuteUbergraph_WB_MapCyclePreview");

	Params::WB_MapCyclePreview_C_ExecuteUbergraph_WB_MapCyclePreview Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

