#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_SliderWithLabel

#include "Basic.hpp"

#include "WB_SliderWithLabel_classes.hpp"
#include "WB_SliderWithLabel_parameters.hpp"


namespace SDK
{

// Function WB_SliderWithLabel.WB_SliderWithLabel_C.RealValueToValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Param_RealValue                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::RealValueToValue(double Param_RealValue, double* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "RealValueToValue");

	Params::WB_SliderWithLabel_C_RealValueToValue Parms{};

	Parms.Param_RealValue = Param_RealValue;

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.ValueToRealValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_RealValue                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::ValueToRealValue(double Value, double* Param_RealValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "ValueToRealValue");

	Params::WB_SliderWithLabel_C_ValueToRealValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_RealValue != nullptr)
		*Param_RealValue = Parms.Param_RealValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.GetMinutes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWB_SliderWithLabel_C::GetMinutes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "GetMinutes");

	Params::WB_SliderWithLabel_C_GetMinutes Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.GetSeconds
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWB_SliderWithLabel_C::GetSeconds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "GetSeconds");

	Params::WB_SliderWithLabel_C_GetSeconds Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.RoundToStepSize
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UWB_SliderWithLabel_C::RoundToStepSize(double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "RoundToStepSize");

	Params::WB_SliderWithLabel_C_RoundToStepSize Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.GetOptionsOverrideIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Param_Index                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::GetOptionsOverrideIndex(double Value, double* Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "GetOptionsOverrideIndex");

	Params::WB_SliderWithLabel_C_GetOptionsOverrideIndex Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Index != nullptr)
		*Param_Index = Parms.Param_Index;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.SetRealValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::SetRealValue(double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "SetRealValue");

	Params::WB_SliderWithLabel_C_SetRealValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWB_SliderWithLabel_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnFocusReceived");

	Params::WB_SliderWithLabel_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.Get_ValueSlider_Value_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWB_SliderWithLabel_C::Get_ValueSlider_Value_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "Get_ValueSlider_Value_0");

	Params::WB_SliderWithLabel_C_Get_ValueSlider_Value_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.Get_ValueLabel_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWB_SliderWithLabel_C::Get_ValueLabel_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "Get_ValueLabel_Text_0");

	Params::WB_SliderWithLabel_C_Get_ValueLabel_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.ChangeRealValue
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  ValueChange                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::ChangeRealValue(double ValueChange)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "ChangeRealValue");

	Params::WB_SliderWithLabel_C_ChangeRealValue Parms{};

	Parms.ValueChange = ValueChange;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.DecreaseRealValue
// (BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::DecreaseRealValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "DecreaseRealValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.IncreaseRealValue
// (BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::IncreaseRealValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "IncreaseRealValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature");

	Params::WB_SliderWithLabel_C_BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "Tick");

	Params::WB_SliderWithLabel_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "PreConstruct");

	Params::WB_SliderWithLabel_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.CustomRight
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::CustomRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "CustomRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.CustomLeft
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::CustomLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "CustomLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureBeginEvent__DelegateSignature
// (BlueprintEvent)

void UWB_SliderWithLabel_C::BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureBeginEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureBeginEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UWB_SliderWithLabel_C::BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "BndEvt__ValueSlider_K2Node_ComponentBoundEvent_0_OnMouseCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWB_SliderWithLabel_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnFocusLost");

	Params::WB_SliderWithLabel_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnControllerCaptureEnd__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::OnControllerCaptureEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnControllerCaptureEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnControllerCaptureBegin__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::OnControllerCaptureBegin__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnControllerCaptureBegin__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnMouseCaptureEnd__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::OnMouseCaptureEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnMouseCaptureEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnMouseCaptureBegin__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_SliderWithLabel_C::OnMouseCaptureBegin__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnMouseCaptureBegin__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.OnRealValueChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Param_RealValue                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::OnRealValueChanged__DelegateSignature(double Param_RealValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "OnRealValueChanged__DelegateSignature");

	Params::WB_SliderWithLabel_C_OnRealValueChanged__DelegateSignature Parms{};

	Parms.Param_RealValue = Param_RealValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_SliderWithLabel.WB_SliderWithLabel_C.ExecuteUbergraph_WB_SliderWithLabel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_SliderWithLabel_C::ExecuteUbergraph_WB_SliderWithLabel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_SliderWithLabel_C", "ExecuteUbergraph_WB_SliderWithLabel");

	Params::WB_SliderWithLabel_C_ExecuteUbergraph_WB_SliderWithLabel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

