#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_SelectMod

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_GameModifierCategory_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_SelectMod.WB_SelectMod_C
// 0x0018 (0x02D8 - 0x02C0)
class UWB_SelectMod_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWB_GridButtonGrid_C*                   SkillGrid;                                         // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	E_GameModifierCategory                        CurrentCategory;                                   // 0x02D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ApplyChanges();
	void ExecuteUbergraph_WB_SelectMod(int32 EntryPoint);
	ESlateVisibility Get_LeftShoulderIcon_Visibility_0();
	class UUserWidget* GetInitialFocusWidget();
	class UPanelWidget* GetPanelWidget();
	void Init();
	void RefreshModList();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_SelectMod_C">();
	}
	static class UWB_SelectMod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_SelectMod_C>();
	}
};
static_assert(alignof(UWB_SelectMod_C) == 0x000008, "Wrong alignment on UWB_SelectMod_C");
static_assert(sizeof(UWB_SelectMod_C) == 0x0002D8, "Wrong size on UWB_SelectMod_C");
static_assert(offsetof(UWB_SelectMod_C, UberGraphFrame) == 0x0002C0, "Member 'UWB_SelectMod_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_SelectMod_C, SkillGrid) == 0x0002C8, "Member 'UWB_SelectMod_C::SkillGrid' has a wrong offset!");
static_assert(offsetof(UWB_SelectMod_C, CurrentCategory) == 0x0002D0, "Member 'UWB_SelectMod_C::CurrentCategory' has a wrong offset!");

}

