#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ServerInfo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_ServerInfo.WB_ServerInfo_C
// 0x0018 (0x02D8 - 0x02C0)
class UWB_ServerInfo_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWB_Button_C*                           Back;                                              // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ServerInfoListScroll;                              // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__Back_K2Node_ComponentBoundEvent_13_Clicked__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_WB_ServerInfo(int32 EntryPoint);
	void RefreshServerStats();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_ServerInfo_C">();
	}
	static class UWB_ServerInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_ServerInfo_C>();
	}
};
static_assert(alignof(UWB_ServerInfo_C) == 0x000008, "Wrong alignment on UWB_ServerInfo_C");
static_assert(sizeof(UWB_ServerInfo_C) == 0x0002D8, "Wrong size on UWB_ServerInfo_C");
static_assert(offsetof(UWB_ServerInfo_C, UberGraphFrame) == 0x0002C0, "Member 'UWB_ServerInfo_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWB_ServerInfo_C, Back) == 0x0002C8, "Member 'UWB_ServerInfo_C::Back' has a wrong offset!");
static_assert(offsetof(UWB_ServerInfo_C, ServerInfoListScroll) == 0x0002D0, "Member 'UWB_ServerInfo_C::ServerInfoListScroll' has a wrong offset!");

}

