#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_FlyingEyeParameters

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function B_FlyingEyeParameters.B_FlyingEyeParameters_C.GetFormattedTooltip
// 0x0088 (0x0088 - 0x0000)
struct B_FlyingEyeParameters_C_GetFormattedTooltip final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0010(0x0010)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0020(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0068(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0010)()
};
static_assert(alignof(B_FlyingEyeParameters_C_GetFormattedTooltip) == 0x000008, "Wrong alignment on B_FlyingEyeParameters_C_GetFormattedTooltip");
static_assert(sizeof(B_FlyingEyeParameters_C_GetFormattedTooltip) == 0x000088, "Wrong size on B_FlyingEyeParameters_C_GetFormattedTooltip");
static_assert(offsetof(B_FlyingEyeParameters_C_GetFormattedTooltip, ReturnValue) == 0x000000, "Member 'B_FlyingEyeParameters_C_GetFormattedTooltip::ReturnValue' has a wrong offset!");
static_assert(offsetof(B_FlyingEyeParameters_C_GetFormattedTooltip, CallFunc_MakeLiteralText_ReturnValue) == 0x000010, "Member 'B_FlyingEyeParameters_C_GetFormattedTooltip::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_FlyingEyeParameters_C_GetFormattedTooltip, K2Node_MakeStruct_FormatArgumentData) == 0x000020, "Member 'B_FlyingEyeParameters_C_GetFormattedTooltip::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(B_FlyingEyeParameters_C_GetFormattedTooltip, K2Node_MakeArray_Array) == 0x000068, "Member 'B_FlyingEyeParameters_C_GetFormattedTooltip::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(B_FlyingEyeParameters_C_GetFormattedTooltip, CallFunc_Format_ReturnValue) == 0x000078, "Member 'B_FlyingEyeParameters_C_GetFormattedTooltip::CallFunc_Format_ReturnValue' has a wrong offset!");

}

