#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Timer

#include "Basic.hpp"

#include "B_Timer_classes.hpp"
#include "B_Timer_parameters.hpp"


namespace SDK
{

// Function B_Timer.B_Timer_C.ExecuteUbergraph_B_Timer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_Timer_C::ExecuteUbergraph_B_Timer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "ExecuteUbergraph_B_Timer");

	Params::B_Timer_C_ExecuteUbergraph_B_Timer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Timer.B_Timer_C.OnFinished__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UB_Timer_C::OnFinished__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "OnFinished__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Timer.B_Timer_C.OnSecondElapsed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ElapsedSeconds                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RemainingSeconds_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_Timer_C::OnSecondElapsed__DelegateSignature(int32 ElapsedSeconds, int32 RemainingSeconds_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "OnSecondElapsed__DelegateSignature");

	Params::B_Timer_C_OnSecondElapsed__DelegateSignature Parms{};

	Parms.ElapsedSeconds = ElapsedSeconds;
	Parms.RemainingSeconds_0 = RemainingSeconds_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Timer.B_Timer_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_Timer_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "ReceiveTick");

	Params::B_Timer_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Timer.B_Timer_C.Start
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UB_Timer_C::Start(int32 Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "Start");

	Params::B_Timer_C_Start Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Timer.B_Timer_C.Stop
// (Public, BlueprintCallable, BlueprintEvent)

void UB_Timer_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Timer_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}

}

