#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_WagonRed

#include "Basic.hpp"

#include "B_Wagon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_WagonRed.B_WagonRed_C
// 0x0000 (0x05A0 - 0x05A0)
class AB_WagonRed_C final : public AB_Wagon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_WagonRed_C">();
	}
	static class AB_WagonRed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_WagonRed_C>();
	}
};
static_assert(alignof(AB_WagonRed_C) == 0x000010, "Wrong alignment on AB_WagonRed_C");
static_assert(sizeof(AB_WagonRed_C) == 0x0005A0, "Wrong size on AB_WagonRed_C");

}

