#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_Interactable

#include "Basic.hpp"


namespace SDK::Params
{

// Function I_Interactable.I_Interactable_C.GetTooltipText
// 0x0010 (0x0010 - 0x0000)
struct I_Interactable_C_GetTooltipText final
{
public:
	class FText                                   ToolTip;                                           // 0x0000(0x0010)(Parm, OutParm)
};
static_assert(alignof(I_Interactable_C_GetTooltipText) == 0x000008, "Wrong alignment on I_Interactable_C_GetTooltipText");
static_assert(sizeof(I_Interactable_C_GetTooltipText) == 0x000010, "Wrong size on I_Interactable_C_GetTooltipText");
static_assert(offsetof(I_Interactable_C_GetTooltipText, ToolTip) == 0x000000, "Member 'I_Interactable_C_GetTooltipText::ToolTip' has a wrong offset!");

}

