#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_BinkMoviePlayer

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WB_BinkMoviePlayer.WB_BinkMoviePlayer_C.ExecuteUbergraph_WB_BinkMoviePlayer
// 0x0320 (0x0320 - 0x0000)
struct WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              CallFunc_GetDuration_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTotalSeconds_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_DoubleDouble_ReturnValue;        // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSwitchBuild_ReturnValue;                // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0018(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValue_ReturnValue;                     // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Source;                         // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Split_LeftS;                              // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Split_RightS;                             // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Split_ReturnValue;                        // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default;                             // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue;                         // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA[0x6];                                       // 0x00DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValue_ReturnValue_1;                   // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              CallFunc_GetDuration_ReturnValue_1;                // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_Multiply_TimespanFloat_ReturnValue;       // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_GetDuration_ReturnValue_2;                // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Seek_ReturnValue;                         // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetTotalSeconds_ReturnValue_1;            // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_GetTime_ReturnValue;                      // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTotalSeconds_ReturnValue_2;            // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Pause_ReturnValue;                        // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11D[0x3];                                      // 0x011D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Rewind_ReturnValue;                       // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Pause_ReturnValue_1;                      // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPaused_ReturnValue;                     // 0x012A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Pause_ReturnValue_2;                      // 0x012B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue_1;                       // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12D[0x3];                                      // 0x012D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              CallFunc_GetDuration_ReturnValue_3;                // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_GetTime_ReturnValue_1;                    // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_TimespanTimespan_ReturnValue; // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0xF];                                      // 0x0141(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0150(0x00D0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_1;                    // 0x0220(0x00D0)()
	bool                                          CallFunc_OpenUrl_ReturnValue;                      // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x02F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x02F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02F3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x02F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x02F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F6[0x2];                                      // 0x02F6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_NotEqual_DoubleDouble_A_ImplicitCast;     // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_B_ImplicitCast;       // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetValue_InValue_ImplicitCast;            // 0x0310(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer) == 0x000010, "Wrong alignment on WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer");
static_assert(sizeof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer) == 0x000320, "Wrong size on WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, EntryPoint) == 0x000000, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::EntryPoint' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetDuration_ReturnValue) == 0x000008, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetDuration_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetTotalSeconds_ReturnValue) == 0x000010, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetTotalSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_NotEqual_DoubleDouble_ReturnValue) == 0x000014, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_NotEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_IsSwitchBuild_ReturnValue) == 0x000015, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_IsSwitchBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_Event_MyGeometry) == 0x000018, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_Event_InDeltaTime) == 0x000050, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Not_PreBool_ReturnValue) == 0x000054, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetValue_ReturnValue) == 0x000058, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_CustomEvent_Source) == 0x000060, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_CustomEvent_Source' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, Temp_bool_Variable) == 0x000070, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Split_LeftS) == 0x000078, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Split_LeftS' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Split_RightS) == 0x000088, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Split_RightS' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Split_ReturnValue) == 0x000098, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Split_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Concat_StrStr_ReturnValue) == 0x0000A0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0000B0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_Select_Default) == 0x0000C0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_PlayAnimation_ReturnValue) == 0x0000D0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_IsVisible_ReturnValue) == 0x0000D8, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Play_ReturnValue) == 0x0000D9, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Play_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetDynamicMaterial_ReturnValue) == 0x0000E0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetValue_ReturnValue_1) == 0x0000E8, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetDuration_ReturnValue_1) == 0x0000F0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetDuration_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Multiply_TimespanFloat_ReturnValue) == 0x0000F8, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Multiply_TimespanFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetDuration_ReturnValue_2) == 0x000100, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetDuration_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Seek_ReturnValue) == 0x000108, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Seek_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetTotalSeconds_ReturnValue_1) == 0x00010C, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetTotalSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetTime_ReturnValue) == 0x000110, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetTotalSeconds_ReturnValue_2) == 0x000118, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetTotalSeconds_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Pause_ReturnValue) == 0x00011C, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Pause_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000120, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Rewind_ReturnValue) == 0x000128, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Rewind_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Pause_ReturnValue_1) == 0x000129, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Pause_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_IsPaused_ReturnValue) == 0x00012A, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_IsPaused_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Pause_ReturnValue_2) == 0x00012B, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Pause_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Play_ReturnValue_1) == 0x00012C, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Play_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetDuration_ReturnValue_3) == 0x000130, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetDuration_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GetTime_ReturnValue_1) == 0x000138, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GetTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_GreaterEqual_TimespanTimespan_ReturnValue) == 0x000140, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_GreaterEqual_TimespanTimespan_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_MakeStruct_SlateBrush) == 0x000150, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, K2Node_MakeStruct_SlateBrush_1) == 0x000220, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::K2Node_MakeStruct_SlateBrush_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_OpenUrl_ReturnValue) == 0x0002F0, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_OpenUrl_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Not_PreBool_ReturnValue_1) == 0x0002F1, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Not_PreBool_ReturnValue_2) == 0x0002F2, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_BooleanAND_ReturnValue) == 0x0002F3, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_BooleanAND_ReturnValue_1) == 0x0002F4, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_BooleanAND_ReturnValue_2) == 0x0002F5, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_NotEqual_DoubleDouble_A_ImplicitCast) == 0x0002F8, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_NotEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Divide_DoubleDouble_B_ImplicitCast) == 0x000300, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Divide_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x000308, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer, CallFunc_SetValue_InValue_ImplicitCast) == 0x000310, "Member 'WB_BinkMoviePlayer_C_ExecuteUbergraph_WB_BinkMoviePlayer::CallFunc_SetValue_InValue_ImplicitCast' has a wrong offset!");

// Function WB_BinkMoviePlayer.WB_BinkMoviePlayer_C.PlayMovie
// 0x0010 (0x0010 - 0x0000)
struct WB_BinkMoviePlayer_C_PlayMovie final
{
public:
	class FString                                 Source;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_BinkMoviePlayer_C_PlayMovie) == 0x000008, "Wrong alignment on WB_BinkMoviePlayer_C_PlayMovie");
static_assert(sizeof(WB_BinkMoviePlayer_C_PlayMovie) == 0x000010, "Wrong size on WB_BinkMoviePlayer_C_PlayMovie");
static_assert(offsetof(WB_BinkMoviePlayer_C_PlayMovie, Source) == 0x000000, "Member 'WB_BinkMoviePlayer_C_PlayMovie::Source' has a wrong offset!");

// Function WB_BinkMoviePlayer.WB_BinkMoviePlayer_C.Tick
// 0x003C (0x003C - 0x0000)
struct WB_BinkMoviePlayer_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WB_BinkMoviePlayer_C_Tick) == 0x000004, "Wrong alignment on WB_BinkMoviePlayer_C_Tick");
static_assert(sizeof(WB_BinkMoviePlayer_C_Tick) == 0x00003C, "Wrong size on WB_BinkMoviePlayer_C_Tick");
static_assert(offsetof(WB_BinkMoviePlayer_C_Tick, MyGeometry) == 0x000000, "Member 'WB_BinkMoviePlayer_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WB_BinkMoviePlayer_C_Tick, InDeltaTime) == 0x000038, "Member 'WB_BinkMoviePlayer_C_Tick::InDeltaTime' has a wrong offset!");

}

