#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ConnectionLoss

#include "Basic.hpp"

#include "WB_ConnectionLoss_classes.hpp"
#include "WB_ConnectionLoss_parameters.hpp"


namespace SDK
{

// Function WB_ConnectionLoss.WB_ConnectionLoss_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_ConnectionLoss_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConnectionLoss_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_ConnectionLoss.WB_ConnectionLoss_C.ExecuteUbergraph_WB_ConnectionLoss
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ConnectionLoss_C::ExecuteUbergraph_WB_ConnectionLoss(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConnectionLoss_C", "ExecuteUbergraph_WB_ConnectionLoss");

	Params::WB_ConnectionLoss_C_ExecuteUbergraph_WB_ConnectionLoss Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_ConnectionLoss.WB_ConnectionLoss_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_ConnectionLoss_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ConnectionLoss_C", "Tick");

	Params::WB_ConnectionLoss_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

