#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_FlyingEye

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AB_FlyingEye.AB_FlyingEye_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_FlyingEye_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AB_FlyingEye_C_AnimGraph) == 0x000008, "Wrong alignment on AB_FlyingEye_C_AnimGraph");
static_assert(sizeof(AB_FlyingEye_C_AnimGraph) == 0x000010, "Wrong size on AB_FlyingEye_C_AnimGraph");
static_assert(offsetof(AB_FlyingEye_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'AB_FlyingEye_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function AB_FlyingEye.AB_FlyingEye_C.ExecuteUbergraph_AB_FlyingEye
// 0x0004 (0x0004 - 0x0000)
struct AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye) == 0x000004, "Wrong alignment on AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye");
static_assert(sizeof(AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye) == 0x000004, "Wrong size on AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye");
static_assert(offsetof(AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye, EntryPoint) == 0x000000, "Member 'AB_FlyingEye_C_ExecuteUbergraph_AB_FlyingEye::EntryPoint' has a wrong offset!");

}

