#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_ObjectiveWitch

#include "Basic.hpp"

#include "B_ObjectiveWitch_classes.hpp"
#include "B_ObjectiveWitch_parameters.hpp"


namespace SDK
{

// Function B_ObjectiveWitch.B_ObjectiveWitch_C.AfterPossess
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Rotation                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_ObjectiveWitch_C::AfterPossess(double Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ObjectiveWitch_C", "AfterPossess");

	Params::B_ObjectiveWitch_C_AfterPossess Parms{};

	Parms.Rotation = Rotation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ObjectiveWitch.B_ObjectiveWitch_C.ExecuteUbergraph_B_ObjectiveWitch
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_ObjectiveWitch_C::ExecuteUbergraph_B_ObjectiveWitch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ObjectiveWitch_C", "ExecuteUbergraph_B_ObjectiveWitch");

	Params::B_ObjectiveWitch_C_ExecuteUbergraph_B_ObjectiveWitch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_ObjectiveWitch.B_ObjectiveWitch_C.InitializeSkinContent
// (Public, BlueprintCallable, BlueprintEvent)

void AB_ObjectiveWitch_C::InitializeSkinContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ObjectiveWitch_C", "InitializeSkinContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_ObjectiveWitch.B_ObjectiveWitch_C.OnRep_Hidden
// (BlueprintCallable, BlueprintEvent)

void AB_ObjectiveWitch_C::OnRep_Hidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ObjectiveWitch_C", "OnRep_Hidden");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_ObjectiveWitch.B_ObjectiveWitch_C.Unhide
// (BlueprintCallable, BlueprintEvent)

void AB_ObjectiveWitch_C::Unhide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_ObjectiveWitch_C", "Unhide");

	UObject::ProcessEvent(Func, nullptr);
}

}

