#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_SofaPillow02

#include "Basic.hpp"

#include "B_SofaPillow_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_SofaPillow02.B_SofaPillow02_C
// 0x0000 (0x0590 - 0x0590)
class AB_SofaPillow02_C final : public AB_SofaPillow_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_SofaPillow02_C">();
	}
	static class AB_SofaPillow02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_SofaPillow02_C>();
	}
};
static_assert(alignof(AB_SofaPillow02_C) == 0x000010, "Wrong alignment on AB_SofaPillow02_C");
static_assert(sizeof(AB_SofaPillow02_C) == 0x000590, "Wrong size on AB_SofaPillow02_C");

}

