#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_VoodooEndInteractionActor

#include "Basic.hpp"

#include "B_VoodooEndInteractionActor_classes.hpp"
#include "B_VoodooEndInteractionActor_parameters.hpp"


namespace SDK
{

// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.Act
// (Public, BlueprintCallable, BlueprintEvent)

void AB_VoodooEndInteractionActor_C::Act()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "Act");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.BndEvt__FireTimer_K2Node_ComponentBoundEvent_0_OnFinished__DelegateSignature
// (BlueprintEvent)

void AB_VoodooEndInteractionActor_C::BndEvt__FireTimer_K2Node_ComponentBoundEvent_0_OnFinished__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "BndEvt__FireTimer_K2Node_ComponentBoundEvent_0_OnFinished__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.ExecuteUbergraph_B_VoodooEndInteractionActor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_VoodooEndInteractionActor_C::ExecuteUbergraph_B_VoodooEndInteractionActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "ExecuteUbergraph_B_VoodooEndInteractionActor");

	Params::B_VoodooEndInteractionActor_C_ExecuteUbergraph_B_VoodooEndInteractionActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.React
// (Public, BlueprintCallable, BlueprintEvent)

void AB_VoodooEndInteractionActor_C::React()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "React");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_VoodooEndInteractionActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_VoodooEndInteractionActor.B_VoodooEndInteractionActor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_VoodooEndInteractionActor_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_VoodooEndInteractionActor_C", "ReceiveTick");

	Params::B_VoodooEndInteractionActor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

