#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IAttachComponent

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IAttachComponent.IAttachComponent_C
// 0x0000 (0x0028 - 0x0028)
class IIAttachComponent_C final : public IInterface
{
public:
	void GetAttachComponent(class USceneComponent** Component);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IAttachComponent_C">();
	}
	static class IIAttachComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IIAttachComponent_C>();
	}
};
static_assert(alignof(IIAttachComponent_C) == 0x000008, "Wrong alignment on IIAttachComponent_C");
static_assert(sizeof(IIAttachComponent_C) == 0x000028, "Wrong size on IIAttachComponent_C");

}

