#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITabable

#include "Basic.hpp"

#include "ITabable_classes.hpp"
#include "ITabable_parameters.hpp"


namespace SDK
{

// Function ITabable.ITabable_C.GetActiveTab
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ActiveTab                                              (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IITabable_C::GetActiveTab(class UWidget** ActiveTab)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITabable_C", "GetActiveTab");

	Params::ITabable_C_GetActiveTab Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ActiveTab != nullptr)
		*ActiveTab = Parms.ActiveTab;
}


// Function ITabable.ITabable_C.GetShouldGoBackAfterAction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool IITabable_C::GetShouldGoBackAfterAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITabable_C", "GetShouldGoBackAfterAction");

	Params::ITabable_C_GetShouldGoBackAfterAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

