#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_HelpHunterSkill

#include "Basic.hpp"

#include "WB_HelpHunterSkill_classes.hpp"
#include "WB_HelpHunterSkill_parameters.hpp"


namespace SDK
{

// Function WB_HelpHunterSkill.WB_HelpHunterSkill_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_HelpHunterSkill_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HelpHunterSkill_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HelpHunterSkill.WB_HelpHunterSkill_C.ExecuteUbergraph_WB_HelpHunterSkill
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HelpHunterSkill_C::ExecuteUbergraph_WB_HelpHunterSkill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HelpHunterSkill_C", "ExecuteUbergraph_WB_HelpHunterSkill");

	Params::WB_HelpHunterSkill_C_ExecuteUbergraph_WB_HelpHunterSkill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HelpHunterSkill.WB_HelpHunterSkill_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWB_HelpHunterSkill_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HelpHunterSkill_C", "OnFocusReceived");

	Params::WB_HelpHunterSkill_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

