#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ServerListBase

#include "Basic.hpp"

#include "WB_ServerListBase_classes.hpp"
#include "WB_ServerListBase_parameters.hpp"


namespace SDK
{

// Function WB_ServerListBase.WB_ServerListBase_C.AddServerRowEOS
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FOnlineSessionSearchResultBP     SearchResult                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    IsCustom                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UserGeneratedContent                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UB_ServerRowData_C*               ServerRowData                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWB_ServerListBase_C::AddServerRowEOS(const struct FOnlineSessionSearchResultBP& SearchResult, bool IsCustom, bool UserGeneratedContent, class UB_ServerRowData_C** ServerRowData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ServerListBase_C", "AddServerRowEOS");

	Params::WB_ServerListBase_C_AddServerRowEOS Parms{};

	Parms.SearchResult = std::move(SearchResult);
	Parms.IsCustom = IsCustom;
	Parms.UserGeneratedContent = UserGeneratedContent;

	UObject::ProcessEvent(Func, &Parms);

	if (ServerRowData != nullptr)
		*ServerRowData = Parms.ServerRowData;
}


// Function WB_ServerListBase.WB_ServerListBase_C.HandleServersFoundEOS
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FOnlineSessionSearchResultBP>Servers                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWB_ServerListBase_C::HandleServersFoundEOS(TArray<struct FOnlineSessionSearchResultBP>& Servers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ServerListBase_C", "HandleServersFoundEOS");

	Params::WB_ServerListBase_C_HandleServersFoundEOS Parms{};

	Parms.Servers = std::move(Servers);

	UObject::ProcessEvent(Func, &Parms);

	Servers = std::move(Parms.Servers);
}


// Function WB_ServerListBase.WB_ServerListBase_C.HandleServerFoundEOS
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FOnlineSessionSearchResultBP     CurrentServer                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// class UB_ServerRowData_C*               ServerEowData                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWB_ServerListBase_C::HandleServerFoundEOS(const struct FOnlineSessionSearchResultBP& CurrentServer, class UB_ServerRowData_C** ServerEowData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_ServerListBase_C", "HandleServerFoundEOS");

	Params::WB_ServerListBase_C_HandleServerFoundEOS Parms{};

	Parms.CurrentServer = std::move(CurrentServer);

	UObject::ProcessEvent(Func, &Parms);

	if (ServerEowData != nullptr)
		*ServerEowData = Parms.ServerEowData;
}

}

